apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: vamsicoswpythonflaskdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vamsicoswpythonflaskdocker 
    spec:
      containers:
        - name: vamsicoswpythonflaskdocker 
          image: aksregistry86225.azurecr.io/vamsicoswpythonflaskdocker
          ports:
          - containerPort: 8080